import '../Styles/globals.scss'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'

import NavBar from '@/components/NavBar/NavBar'
import Ligth from '@/components/Ligth/Ligth'
import { SkeletonTheme } from 'react-loading-skeleton'
import 'react-loading-skeleton/dist/skeleton.css'

const figtree = Figtree({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
  title: 'Shamy Movie Application',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={figtree.className}>
        <SkeletonTheme baseColor='#313131' highlightColor='#525252'>
          <NavBar />
          <Ligth left={-150} top={-150} />
          {/* <Ligth id={2}/> */}
          {children}
        </SkeletonTheme>
      </body>
    </html>
  )
}
